config/routes.rb
Rails.application.routes.draw do
# Establish scaffolding for the four tables and their data
  resources :posts
  resources :contact_requests
  resources :profiles
  resources :users

# Set front page as root
  root to: 'users#homepage'
  get '/user_about' => 'users#about'

# Manage the first interaction with the user registering by routing to the registration form
  get '/user_new' => 'users#new'
  post '/user_new' => 'users#create'

# Manage the logon screen
  get '/user_login' => 'sessions#new'
  post '/user_login' => 'sessions#create'
  get 'user_logout' => 'sessions#destroy'
  post '/user_logout' => 'sessions#destroy'

# Manage the link to the profile page via a new profile form
  get '/profile_new' => 'profiles#new'
  post '/profile_new' => 'profiles#create'
  get '/profile_show' => 'profiles#show'
  get '/profile_edit' => 'profiles#edit'
  patch '/profile_path' => 'profiles#update'

# Manage the link to the profile search page
  get '/profile_search' => 'profiles#search'

# Manage the link to the new contact request page via a form
  delete '/user_destroy' => 'users#destroy'
  get '/user_new' => 'users#new'
  post '/user' => 'users#create'
  patch 'user_update' => 'users#update'
  get '/user_edit' => 'users#edit'

# Manage the link to the show contact requests

# Manage the link to the Messages screen

# Manage the link to the new message screen via a form

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # Set up relationship to user table
  belongs_to :user

  # Validation for the profile table fields
  validates :username, presence: true, length: {minimum: 8, maximum: 50}
  validates :address, presence: true, length: {minimum: 8, maximum: 50}
  validates :suburb, presence: true, length: {minimum: 2, maximum: 30}
  validates :postcode, presence: true, length: {minimum: 4, maximum: 4}
  validates :search_radius, presence: true, length: {minimum: 1, maximum: 4}
  validates :age, presence: true, length: {maximum: 3}
  validates :sex, presence: true, length: {maximum: 4}
  validates :interests, presence: true, length: {minimum: 1, maximum:100}
end

app/controllers/profiles_controller.rb
# The profiles controller manages the users individual profiles.
# It includes creating, showing, editing, updating and deleting profiles.
class ProfilesController < ApplicationController

  # GET /profiles
  def index
    if current_user && current_user.profile.nil?
      redirect_to :action => 'new'
    end
  end

  # GET /profiles/1
  def search
    # Finding Profile for logged in user
    @profile = Profile.find_by user_id: 'current_user.id'

    # # grabbing API
    @searcher = current_user.profile.postcode.to_s

    suburbs = HTTParty.get('http://v0.postcodeapi.com.au/suburbs/'+@searcher+'.json')
    @suburbs = suburbs
    result = @suburbs[0]['latitude']
    result2 = @suburbs[0]['longitude']

    # making accessible by ERB under a variable
      @result = result.to_s
      @result2 = result2.to_s

    @radius_current_user = current_user.profile.search_radius.to_s
    radius = HTTParty.get('http://v0.postcodeapi.com.au/radius.json?distance='+@radius_current_user+'&latitude='+@result+'&longitude='+@result2+'')

    @radius = radius
    @result3 = @radius[0]['postcode']

    @result4 = Profile.where(:postcode => @result3)

    @result5 = []
    @result4.each do |e|
      @result5.push(e.username)
    end

  end

  # GET /profiles/new
  def new

  end

  # GET /profiles/1/edit
  def edit

  end

  # POST /profiles
  def create
    @profile = Profile.create(profile_params)
    @profile.user_id = current_user.id
    @profile.save
    session[:profile_id] = @profile.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to '/profile_show', notice: 'Profile was successfully created.' }
      else
        flash[:errors] = @profile.errors.full_messages.join(', ')
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /profiles/1
  def update
    current_user.profile.update_attributes(profile_params)
    redirect_to profile_show_path(current_user)
  end

  # DELETE /profiles/1
  def destroy
    current_user.profile.delete
    flash[:message] = "Profile successfully deleted"
    redirect_to user_logout_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_profile
    #   @profile = Profile.find(session[:profile_id])
    # end

    # Use the below definition to shorten the code parameters for several actions.
    def profile_params
      params.require(:profile).permit(:username, :address, :suburb, :postcode, :search_radius, :sex, :age, :interests, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<h1>Edit User and Profile</h1>

<%= form_for(current_user) do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% current_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :suburb %><br>
    <%= f.text_field :suburb %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.number_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :search_radius %><br>
    <%= f.number_field :search_radius %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :interests %><br>
    <%= f.text_area :interests %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div id="menu_bar">
  <ul>
    <li><a href="/"><h1>Editing <%= current_user.email %></h1></a></li>
    <li><a href="user_about" ><h3>About</h3></a></li>
    <li><a href="/user_login"><h3>Login</h3></a></li>
    <li><a href="/user_new"><h3>Register</h3></a></li>
  </ul>
</div>

<div id="colorstrip2"/>

<div id="reg">
  <%= form_for current_user.profile, url: '/profile_path', method: :patch do |f| %>
    <span><strong>Address: </strong><%= f.text_field :address %></span><br>
    <span><strong>Username: </strong><%= f.text_field :username %></span><br>
    <span><strong>Suburb: </strong><%= f.text_field :suburb %></span><br>
    <span><strong>Postcode: </strong><%= f.number_field :postcode %></span><br>
    <span><strong>Search Radius: </strong><%= f.number_field :search_radius %></span><br>
    <span><strong>Sex: </strong><%= f.select :sex, "<option>M</option><option>F</option>".html_safe %></span><br>
    <span><strong>Age: </strong><%= f.number_field :age %></span><br>
    <span><strong>Interests: </strong><%= f.select :interests, "<option>Cycling</option><option>Sewing</option><option>Reading</option><option>Programming</option>".html_safe %></span><br>
    <%= f.submit "Update My Profile", id: 'buttonmagic'  %>
  <% end %>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Profile</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Address</th>
      <th>Suburb</th>
      <th>Postcode</th>
      <th>Search radius</th>
      <th>Sex</th>
      <th>Age</th>
      <th>Interests</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= @profile.username %></td>
        <td><%= @profile.address %></td>
        <td><%= @profile.suburb %></td>
        <td><%= @profile.postcode %></td>
        <td><%= @profile.search_radius %></td>
        <td><%= @profile.sex %></td>
        <td><%= @profile.age %></td>
        <td><%= @profile.interests %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<div id="menu_bar">
  <ul>
    <li><a href="/"><h1>New Profile</h1></a></li>
    <li><a href="user_about"><h3>About</h3></a></li>
    <li><a href="/user_login"><h3>Login</h3></a></li>
    <li><a href="/user_new"><h3>Register</h3></a></li>
  </ul>
</div>
<div id="colorstrip2"/>
<% if flash[:errors] %>
  <p><%= flash[:errors] %></p>
<% end %>

<div id="reg">
  <%= form_for :profile, url: '/profile_new' do |f| %>
    <span><strong>Address: </strong><%= f.text_field :address %></span><br>
    <span><strong>Username: </strong><%= f.text_field :username %></span><br>
    <span><strong>Suburb: </strong><%= f.text_field :suburb %></span><br>
    <span><strong>Postcode: </strong><%= f.number_field :postcode %></span><br>
    <span><strong>Search Radius: </strong><%= f.number_field :search_radius %></span><br>
    <span><strong>Sex: </strong><%= f.select :sex, "<option>M</option><option>F</option>".html_safe %></span><br>
    <span><strong>Age: </strong><%= f.number_field :age %></span><br>
    <span><strong>Interests: </strong><%= f.select :interests, "<option>Cycling</option><option>Sewing</option><option>Reading</option><option>Programming</option>".html_safe %></span><br>

    <%= f.submit "Submit", id: 'buttonmagic' %>
    <button id='buttonmagic'><%= link_to 'Back', user_edit_path(current_user) %></button>
  <% end %>
</div>

app/views/profiles/search.html.erb
<div id="menu_bar">
  <ul>
    <li><a href="/"><h1>Search Page</h1></a></li>
    <li><a href="user_about"><h3>About</h3></a></li>
    <li><a href="/user_login"><h3>Login</h3></a></li>
    <li><a href="/user_new"><h3>Register</h3></a></li>
  </ul>
</div>
<div id="colorstrip2"/><h3></h3>

<div id="show">
  <span><strong>Suburb: </strong><%= current_user.profile.suburb %></span><br>
  <span><strong>Latitude: </strong><%= @result %></span><br>
  <span><strong>Longitude: </strong><%= @result2 %></span><br>
  <span><strong>Radius: </strong><%= @radius_current_user %></span><br>
  <span><strong>Postcodes: </strong><%= @result3 %></span><br>
  <span><strong>Users in the area: </strong></span><br>
  <span><%= @result5 %></span><br>

<button id='buttonmagic'><%= link_to 'Show Profile', profile_show_path %></button>
<button id='buttonmagic'><%= link_to 'Logout', user_logout_path, method: :post %></button>
</div>

app/views/profiles/show.html.erb
<div id="menu_bar">
  <ul>
    <li><a href="/"><h1>My Profile</h1></a></li>
    <li><a href="user_about"><h3>About</h3></a></li>
    <li><a href="/user_login"><h3>Login</h3></a></li>
    <li><a href="/user_new"><h3>Register</h3></a></li>
  </ul>
</div>
<div id="colorstrip2"/>
<div id="show">
    <span><strong>First name: </strong><%= current_user.first_name %></span><br>
    <span><strong>Last name: </strong><%= current_user.last_name %></span><br>
    <span><strong>Email: </strong><%= current_user.email %></span><br>
    <span><strong>Username: </strong><%= current_user.profile.username %></span><br>
    <span><strong>Address: </strong><%= current_user.profile.address %></span><br>
    <span><strong>Suburb: </strong><%= current_user.profile.suburb %></span><br>
    <span><strong>Postcode: </strong><%= current_user.profile.postcode %></span><br>
    <span><strong>Search radius: </strong><%= current_user.profile.search_radius %></span><br>
    <span><strong>Sex: </strong><%= current_user.profile.sex %></span><br>
    <span><strong>Age: </strong><%= current_user.profile.age %></span><br>
    <span><strong>Interests: </strong><%= current_user.profile.interests %></span><br>

    <button id='buttonmagic'><%= link_to 'Edit Profile', edit_profile_path(current_user) %></button>
    <button id='buttonmagic'><%= link_to 'Delete User', user_path(current_user), method: :delete %></button>
    <button id='buttonmagic'><%= link_to 'Search Profiles', profile_search_path %></button>
    <button id='buttonmagic'><%= link_to 'Logout', user_logout_path, method: :post %></button>
</div>