config/routes.rb
Rails.application.routes.draw do
# Establish scaffolding for the four tables and their data
  resources :posts
  resources :contact_requests
  resources :profiles
  resources :users

# Set front page as root
  root to: 'users#homepage'
  get '/user_about' => 'users#about'

# Manage the first interaction with the user registering by routing to the registration form
  get '/user_new' => 'users#new'
  post '/user_new' => 'users#create'

# Manage the logon screen
  get '/user_login' => 'sessions#new'
  post '/user_login' => 'sessions#create'
  get 'user_logout' => 'sessions#destroy'
  post '/user_logout' => 'sessions#destroy'

# Manage the link to the profile page via a new profile form
  get '/profile_new' => 'profiles#new'
  post '/profile_new' => 'profiles#create'
  get '/profile_show' => 'profiles#show'
  get '/profile_edit' => 'profiles#edit'
  patch '/profile_path' => 'profiles#update'

# Manage the link to the profile search page
  get '/profile_search' => 'profiles#search'

# Manage the link to the new contact request page via a form
  delete '/user_destroy' => 'users#destroy'
  get '/user_new' => 'users#new'
  post '/user' => 'users#create'
  patch 'user_update' => 'users#update'
  get '/user_edit' => 'users#edit'

# Manage the link to the show contact requests

# Manage the link to the Messages screen

# Manage the link to the new message screen via a form

end

app/models/contact_request.rb
class ContactRequest < ActiveRecord::Base
  # Set up relationship to user table
  belongs_to :user

  # Validation for the contact_request table fields
  validates :from, presence: true, length: {minimum: 1, maximum: 50}
  validates :to, presence: true, length: {minimum: 1, maximum: 50}
  validates :request, presence: true, length: {minimum: 1, maximum: 100}
  validates :permission, presence: true
end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController
  before_action :set_contact_request, only: [:show, :edit, :update, :destroy]

  # GET /contact_requests
  # GET /contact_requests.json
  def index
    @contact_requests = ContactRequest.all
  end

  # GET /contact_requests/1
  # GET /contact_requests/1.json
  def show
  end

  # GET /contact_requests/new
  def new
    @contact_request = ContactRequest.new
  end

  # GET /contact_requests/1/edit
  def edit
  end

  # POST /contact_requests
  # POST /contact_requests.json
  def create
    @contact_request = ContactRequest.new(contact_request_params)

    respond_to do |format|
      if @contact_request.save
        format.html { redirect_to @contact_request, notice: 'Contact request was successfully created.' }
        format.json { render :show, status: :created, location: @contact_request }
      else
        format.html { render :new }
        format.json { render json: @contact_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_requests/1
  # PATCH/PUT /contact_requests/1.json
  def update
    respond_to do |format|
      if @contact_request.update(contact_request_params)
        format.html { redirect_to @contact_request, notice: 'Contact request was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_request }
      else
        format.html { render :edit }
        format.json { render json: @contact_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_requests/1
  # DELETE /contact_requests/1.json
  def destroy
    @contact_request.destroy
    respond_to do |format|
      format.html { redirect_to contact_requests_url, notice: 'Contact request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_request
      @contact_request = ContactRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_request_params
      params.fetch(:contact_request, {})
    end
end

app/helpers/contact_requests_helper.rb
module ContactRequestsHelper
end

app/views/contact_requests/_form.html.erb
<%= form_for(@contact_request) do |f| %>
  <% if @contact_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_request.errors.count, "error") %> prohibited this contact_request from being saved:</h2>

      <ul>
      <% @contact_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_requests/edit.html.erb
<h1>Editing Contact Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_request %> |
<%= link_to 'Back', contact_requests_path %>

app/views/contact_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of my Contact Requests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_requests.each do |contact_request| %>
      <tr>
        <td><%= link_to 'Show', contact_request %></td>
        <td><%= link_to 'Edit', edit_contact_request_path(contact_request) %></td>
        <td><%= link_to 'Destroy', contact_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact request', new_contact_request_path %>

app/views/contact_requests/new.html.erb
<h1>New Contact Request</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_requests_path %>

app/views/contact_requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_request_path(@contact_request) %> |
<%= link_to 'Back', contact_requests_path %>