config/routes.rb
Rails.application.routes.draw do
# Establish scaffolding for the four tables and their data
  resources :posts
  resources :contact_requests
  resources :profiles
  resources :users

# Set front page as root
  root to: 'users#homepage'
  get '/user_about' => 'users#about'

# Manage the first interaction with the user registering by routing to the registration form
  get '/user_new' => 'users#new'
  post '/user_new' => 'users#create'

# Manage the logon screen
  get '/user_login' => 'sessions#new'
  post '/user_login' => 'sessions#create'
  get 'user_logout' => 'sessions#destroy'
  post '/user_logout' => 'sessions#destroy'

# Manage the link to the profile page via a new profile form
  get '/profile_new' => 'profiles#new'
  post '/profile_new' => 'profiles#create'
  get '/profile_show' => 'profiles#show'
  get '/profile_edit' => 'profiles#edit'
  patch '/profile_path' => 'profiles#update'

# Manage the link to the profile search page
  get '/profile_search' => 'profiles#search'

# Manage the link to the new contact request page via a form
  delete '/user_destroy' => 'users#destroy'
  get '/user_new' => 'users#new'
  post '/user' => 'users#create'
  patch 'user_update' => 'users#update'
  get '/user_edit' => 'users#edit'

# Manage the link to the show contact requests

# Manage the link to the Messages screen

# Manage the link to the new message screen via a form

end

app/models/user.rb
class User < ActiveRecord::Base
  # Set up relationships to table associated with user table
  has_one :profile
  has_many :contact_requests
  has_many :posts

  # Links in bcrypt to manage password actions
  has_secure_password

  # Validation for the user table fields
  validates :first_name, presence: true, length: {minimum: 1, maximum: 50}
  validates :last_name, presence: true, length: {minimum: 1, maximum: 50}
  validates :email, presence: true, length: {minimum: 1, maximum: 50}

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:edit, :update, :destroy]

  # GET /users
  def index
    # @users = User.all
  end

  # Registration form to manage initial user registration action
  def new
  end

  # GET /users/1
  def show
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    user = User.new(user_params)

      if user.save
        session[:user_id] = user.id
        redirect_to '/profile_new'
      else
        flash[:errors] = { 'class' => 'tribe_error', :errors => user.errors.full_messages }
        redirect_to '/user_new'
      end
    end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_area :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_area :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/about.html.erb
<div id="menu_bar">
  <ul>
    <li><a href="/"><h1>About</h1></a></li>
    <li><a href="user_about"><h3>About</h3></a></li>
    <li><a href="/user_login"><h3>Login</h3></a></li>
    <li><a href="/user_new"><h3>Register</h3></a></li>
  </ul>
</div>
<div id="colorstrip"/>

<div id="about">
  <p>This is a Ruby on Rails project that demonstrates: </p>
  <p>* the use of CRUD </p>
  <p>* integration of an external API</p>
  <p> The site uses the postcode API for managing the translation of postcodes into suburbs and vice versa as well as providing a radius of surrounding suburbs.
      The site is the first part of a minimum viable product being tested for application with users.</p>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/homepage.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Tribe</title>
</head>
<body>
    <div id="menu_bar">
      <ul>
        <li><a href="/"><h1>Tribe</h1></a></li>
        <li><a href="user_about"><h3>About</h3></a></li>
        <li><a href="/user_login"><h3>Login</h3></a></li>
        <li><a href="/user_new"><h3>Register</h3></a></li>
      </ul>
    </div>
  <div class="front_image">
    <%= image_tag("orange-people-silhouettes.jpg") %>
    <p id="front_text">Tribe helps you find people near your home who have the same interests as you with the aim of getting people to meet and form local groups</p>
  </div>
</body>
</html>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.password_confirmation %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div id="menu_bar">
  <ul>
    <li><a href="/"><h1>New Registration</h1></a></li>
    <li><a href="user_about"><h3>About</h3></a></li>
    <li><a href="/user_login"><h3>Login</h3></a></li>
    <li><a href="/user_new"><h3>Register</h3></a></li>
  </ul>
</div>
<div id="colorstrip2"/>
<% if flash[:errors] %>
  <p><%=flash[:errors]['errors'].join(', ') %></p>
<% end %>
<div id="reg">
<%= form_for :user, url: '/user_new' do |f| %>
  <span><strong>Email: </strong><%= f.text_field :email %></span><br>
  <span><strong>First name: </strong><%= f.text_field :first_name %></span><br>
  <span><strong>Last name: </strong><%= f.text_field :last_name %></span><br>
  <span><strong>Password: </strong><%= f.text_field :password %></span><br>
  <span><strong>Password Confirmation: </strong><%= f.password_field :password_confirmation %></span><br>
  <%= f.submit "Submit", id: 'buttonmagic' %>
<% end %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div id="show">
    <span><strong>First name: </strong><%= current_user.first_name %></span><br>
    <span><strong>Last name: </strong><%= current_user.last_name %></span><br>
    <span><strong>Email: </strong><%= current_user.email %></span><br>
</div>

<%= link_to 'Edit', profile_new_path(@user) %> |